// Logo assets (UI-012, UI-014). The files in public/brand/ are generated by
// ui-audit/tools/brand.mjs for both crosses.
//
// The cross is waiting for the priest's choice. Changing it is this one line: "coptic" or "latin".
export const BRAND_CROSS: "coptic" | "latin" = "coptic";

export const BRAND = {
  /** "Learn / ORTHODOXY" with the candle and the tagline "A Coptic Orthodox Study Guide". */
  wordmark: { src: "/brand/wordmark.svg", width: 960, height: 250 },
  /** The same without the tagline, for widths under about 400 px and Arabic pages. */
  wordmarkShort: { src: "/brand/wordmark-short.svg", width: 960, height: 203 },
  /** "LO" with the cross in the O. */
  lettermark: { src: `/brand/lettermark-${BRAND_CROSS}.svg`, width: 556, height: 287 },
  /** The cross alone in antique gold, for section dividers. */
  cross: `/brand/cross-${BRAND_CROSS}.svg`,
  favicon: `/brand/favicon-${BRAND_CROSS}.ico`,
  appleIcon: `/brand/apple-icon-${BRAND_CROSS}.png`,
  appIcon192: `/brand/icon-${BRAND_CROSS}-192.png`,
  appIcon512: `/brand/icon-${BRAND_CROSS}-512.png`,
} as const;
