MANUAL_SAINT_NAME_EXCLUSIONS = {
    "St. Abba Abra",
    "St. Abba Abram",
    "St. Abba Anthony the Great the Father",
    "St. Athanasius the Apostolic",
    "St. Pope Cyril the Great Steps",
    "St. Cyprian Bishop of Carthage",
    "St. Gregory Minor",
    "St. Gregory Nazianzus",
    "St. Gregory the Nazianzus",
    "St. John Chr",
    "St. John Chry",
    "St. John Chrysost",
    "St. Gregoryof Nyssa",
    "St. Hegomen Yassa Michael",
    "St. Who Prohesized",
    "St. Who Prohphesized",
    "St. Who Prophesied",
    "St. Who Prophesized",
}

MANUAL_SAINT_NAME_REPLACEMENTS = {
    "St. AGREGORIUS THE ARMENIAN": "St. Gregory the Armenian",
    "St. AGREGORIUS THE WONDER MAKER": "St. Gregory the Wonderworker",
    "St. Athanasius Testimony": "",
    "St. Clement of Alexa": "St. Clement of Alexandria",
    "St. Cyprian Bishop of Carthage": "St. Cyprian of Carthage",
    "St. Gregory Nazianzus": "St. Gregory of Nazianzus",
    "St. Gregory the Nazianzus": "St. Gregory of Nazianzus",
    "St. Gregoryof Nyssa": "St. Gregory of Nyssa",
    "St. Hilary of Poitier": "St. Hilary of Poitiers",
    "St. John Chr": "St. John Chrysostom",
    "St. John Chry": "St. John Chrysostom",
    "St. John Chrysost": "St. John Chrysostom",
    "St. THOMAS OF AQUINAS": "St. Thomas Aquinas",
    "St. THOMAS OF AQUINAS This Thomas": "St. Thomas Aquinas",
    "St. Pope Cyril the Great Steps": "",
    "St. Cyril Maqar": "",
    "St. Who Prohesized": "",
    "St. Who Prohphesized": "",
    "St. Who Prophesied": "",
    "St. Who Prophesized": "",
}
